name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  nix-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v16
        with:
          name: fzakaria
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build & check
        run: |
          nix fmt -- --check .
          nix build
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Lint
        run: |
          npm ci --dev
          npm run prettier-check
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
